#!/usr/bin/env python3
"""Audit-task status protocol.

Reports the completion status of every task in the triaged audit plan
(``reports/2026-07-textbook-audit.md``) by cross-referencing git history:
a task is "done" when a commit merged into the target branch is tagged with
that task's id.

How tasks are matched
---------------------
Completion commits in this repo tag the task id in their subject line, in
one of two shapes seen in history::

    H2: Rebuild partial-fractions appendix ... (#189)     # id at the start
    Fix confirmed mathematical errata ... (H1) (#187)     # id in parentheses
    H8 (part 1): Backfill missing answers ... (#192)      # multi-part task

The matcher therefore looks for the id as a standalone token anywhere in the
subject (both boundaries = start/end of string or a non-alphanumeric, so
``H1`` never matches ``H10`` or ``H1b``), and records the ``(#NNN)`` pull
request number when present. A task with two or more matching commits (e.g.
``H8``) is reported done with every pull request listed.

Usage
-----
    python3 processing-tools/audit-status/audit_status.py           # print + refresh report block
    python3 processing-tools/audit-status/audit_status.py --print   # print only, do not touch the report
    python3 processing-tools/audit-status/audit_status.py --ref main # match against a different git ref

Running it refreshes the ``AUDIT-STATUS`` block near the top of the report so
the report itself always shows current status; it is idempotent.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT = REPO_ROOT / "reports" / "2026-07-textbook-audit.md"

BEGIN = "<!-- AUDIT-STATUS:BEGIN (generated by processing-tools/audit-status/audit_status.py — do not edit by hand) -->"
END = "<!-- AUDIT-STATUS:END -->"

TASK_HEADER = re.compile(r"^###\s+((?:H|M|L)\d+)\.\s+(.*\S)\s*$")


def git_log_subjects(ref):
    """Return a list of (short_hash, subject) for commits reachable from ref.

    Falls back through origin/main -> main -> HEAD so the tool works whether or
    not a remote-tracking ref is present.
    """
    candidates = [ref] if ref else ["origin/main", "main", "HEAD"]
    last_err = None
    for cand in candidates:
        try:
            out = subprocess.run(
                ["git", "-C", str(REPO_ROOT), "log", "--format=%h\x1f%s", cand],
                capture_output=True, text=True, check=True,
            ).stdout
            rows = []
            for line in out.splitlines():
                if "\x1f" in line:
                    h, s = line.split("\x1f", 1)
                    rows.append((h, s))
            return cand, rows
        except subprocess.CalledProcessError as exc:
            last_err = exc
    raise SystemExit(f"could not read git log from any of {candidates}: {last_err}")


def parse_tasks(report_text):
    """Return an ordered list of (id, title, priority) parsed from the report."""
    priority = None
    tasks = []
    for line in report_text.splitlines():
        low = line.strip().lower()
        if low.startswith("## high priority"):
            priority = "High"
        elif low.startswith("## medium priority"):
            priority = "Medium"
        elif low.startswith("## low priority"):
            priority = "Low"
        elif low.startswith("## "):
            # any other H2 section (overview, caveats, appendix, future) ends task capture
            priority = None
        m = TASK_HEADER.match(line)
        if m and priority:
            tasks.append((m.group(1), m.group(2), priority))
    return tasks


def match_status(task_id, subjects):
    """Return a list of pull-request labels for commits completing task_id."""
    # id as a standalone token: not preceded or followed by an alphanumeric.
    token = re.compile(r"(?<![0-9A-Za-z])" + re.escape(task_id) + r"(?![0-9A-Za-z])")
    pr = re.compile(r"\(#(\d+)\)")
    hits = []
    for h, subj in subjects:
        if token.search(subj):
            m = pr.search(subj)
            hits.append("#" + m.group(1) if m else h)
    return hits


def build_block(tasks, subjects, ref):
    rows = []
    counts = {"High": [0, 0], "Medium": [0, 0], "Low": [0, 0]}
    for tid, title, prio in tasks:
        hits = match_status(tid, subjects)
        done = bool(hits)
        counts[prio][1] += 1
        if done:
            counts[prio][0] += 1
        status = "✅ done" if done else "⬜ pending"
        merged = ", ".join(dict.fromkeys(hits)) if hits else "—"
        short = title if len(title) <= 68 else title[:65] + "…"
        rows.append(f"| {tid} | {status} | {merged} | {short} |")

    lines = [BEGIN, "", "## Task status", "",
             f"_Generated by `processing-tools/audit-status/audit_status.py` "
             f"against `{ref}`. Re-run it to refresh._", "",
             "| Task | Status | Merged as | Title |",
             "|------|--------|-----------|-------|"]
    lines += rows
    lines.append("")
    summary = " &nbsp;·&nbsp; ".join(
        f"**{p}:** {counts[p][0]}/{counts[p][1]} done" for p in ("High", "Medium", "Low")
    )
    total_done = sum(counts[p][0] for p in counts)
    total = sum(counts[p][1] for p in counts)
    lines.append(f"{summary} &nbsp;·&nbsp; **Overall:** {total_done}/{total}.")
    lines.append("")
    lines.append(END)
    return "\n".join(lines), counts


def splice(report_text, block):
    """Insert or replace the AUDIT-STATUS block, returning the new report text."""
    if BEGIN in report_text and END in report_text:
        pre = report_text[: report_text.index(BEGIN)]
        post = report_text[report_text.index(END) + len(END):]
        return pre + block + post
    # first run: insert after the first horizontal rule that follows the intro
    marker = "\n---\n"
    idx = report_text.find(marker)
    if idx == -1:
        return report_text.rstrip() + "\n\n" + block + "\n"
    cut = idx + len(marker)
    return report_text[:cut] + "\n" + block + "\n" + report_text[cut:]


def main():
    ap = argparse.ArgumentParser(description="Report audit-task completion status.")
    ap.add_argument("--print", dest="print_only", action="store_true",
                    help="print the status table only; do not modify the report")
    ap.add_argument("--ref", default=None,
                    help="git ref to match completions against (default: origin/main, then main, then HEAD)")
    args = ap.parse_args()

    report_text = REPORT.read_text(encoding="utf-8")
    tasks = parse_tasks(report_text)
    if not tasks:
        raise SystemExit(f"no tasks parsed from {REPORT}")
    ref, subjects = git_log_subjects(args.ref)
    block, counts = build_block(tasks, subjects, ref)

    print(block.replace(BEGIN, "").replace(END, "").strip())

    if not args.print_only:
        new_text = splice(report_text, block)
        if new_text != report_text:
            REPORT.write_text(new_text, encoding="utf-8")
            print(f"\n[updated {REPORT.relative_to(REPO_ROOT)} status block]", file=sys.stderr)
        else:
            print(f"\n[{REPORT.relative_to(REPO_ROOT)} already up to date]", file=sys.stderr)


if __name__ == "__main__":
    main()
